resources:      
  repositories: 
  - repository: NodeYaml
    name: gx-devops-yamls/NodeYaml
    type: git 
    ref: master #branch name

trigger: none
extends:
  template: NodePipeline.yaml@NodeYaml