SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SellerPlan]
(
  [SellerId] [int] NOT NULL,
  [Sku] [varchar](255) NOT NULL,
  [TrialDays] [smallint] NOT NULL,
  CONSTRAINT FK_SellerId_SellerPlan_Seller FOREIGN KEY (SellerId)
  REFERENCES [dbo].[Seller] (SellerId)
) ON [PRIMARY]

GO

CREATE UNIQUE NONCLUSTERED INDEX [SellerPlanSellerIdSku] ON [dbo].[SellerPlan]
(
	[SellerId] ASC,
	[Sku] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO