name: Version
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: GetVersion
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The  Version was ${{ steps.package-version.outputs.current-version}}'